const actionType = {

  HIDE_LOADING: "HIDE_LOADING",
  SHOW_LOADING: "SHOW_LOADING",
  ADMIN_LOGIN_SUCCESS: "ADMIN_LOGIN_SUCCESS",
  ADMIN_LOGIN_FAILURE: "ADMIN_LOGIN_FAILURE",
  CUSTOMER_REGISTER_SUCCESS: "CUSTOMER_REGISTER_SUCCESS",
  CUSTOMER_REGISTER_FAIL: "CUSTOMER_REGISTER_FAIL",
  ACCOUNT_VERIFIED: "ACCOUNT_VERIFIED",
  ACCOUNT_VERIFIED_FAIL: "ACCOUNT_VERIFIED_FAIL",
  CLIENT_LOGIN_SUCCESS: "CLIENT_LOGIN_SUCCESS",
  CLIENT_LOGIN_FAILURE: "CLIENT_LOGIN_FAILURE",
  SET_LANGUAGE_SUCCESS: "SET_LANGUAGE_SUCCESS"
};

export default actionType;