const initialState = {
      registrationStatus : false,
      getContactandAddressListData : null,
      getContactandAddressListStatus : false,
      addContactandAddressListStatus: false,
      getViewAccessHistoryListData : null,
      getViewAccessHistoryListStatus :false,
      subscriptionValue :  false,
      subscribedPlanDetails : null,
      subscribedPlanStatus : false,
      freeSubscribedPlanDetails : null,
      freeSubscribedPlanStatus : false,
      getKYCDetails : null,
      getKYCDetailsStatus : false,
      getTransactionListStatus : false,
      getTransactionListData : null,
      downgradeRequestPlanDetails : null,
      downgradeRequestPlanStatus : false,
      downgradeRequestStatus : false,
      sendRequestMoneyTransactionStatus : false,
      //EDITED ......
      getMerchantPOSStatus : false,
      addSMStatus : false,
      getShopManagersListStatus : false,
      shopManagerStatus:true,
      getPOSListStatus : false,
      listData:null,
      status:false,
      getShopManagerEmailVerificationStatus : true,
      getPOSManagerEmailVerificationStatus : true,
      updateShopManagerStatus : false,
      getPushNotificationStatus : false,
      getPOSStatus : false,
      profile:null,
      sendOtp:false,
      proPicStatus : false,
      proPicData : [],
      viewProPicMerchantData:[],
      addKYCStatus:false,
      getTransactionDetailsStatus:false,
      getTransactionDetails : null,
      transactionDetailsStatus:false,
      transactionDetails : null,
      PermissionListData:null,
      PermissionStatus:false,
      merchantSendOtp:false,
      merchantSendEmail:false,
      merchantLoginStatus:false,
      getSubscriptionListData:[],
      getSubscriptionListDataStatus:false,
      getPaymentCategoriesListData:[],
      getPaymentMethodsListData:[],
      getTicketListData:[],
      getTicketListData:false,
      message: null,
    //   viewProPicStatus: false
  };
  export default initialState;