const actionType = {
    AGENT_LOGIN_SUCCESS: "AGENT_LOGIN_SUCCESS",
    AGENT_LOGIN_FAILURE: "AGENT_LOGIN_FAILURE",
    AGENT_LINKING_SUCCESS:"AGENT_LINKING_SUCCESS",
    AGENT_LINKING_FAILURE:"AGENT_LINKING_FAILURE",

    /**
    *
    */
    AGENT_PROFILE_FETCH: 'AGENT_PROFILE/fetch',
    AGENT_PROFILE_DATA: 'AGENT_PROFILE/data',
    AGENT_PROFILE_ERROR: 'AGENT_PROFILE/error',

    AGENT_WALLET_ACCOUNT_FETCH: 'AGENT_WALLET_ACCOUNT/fetch',
    AGENT_WALLET_ACCOUNT_DATA: 'AGENT_WALLET_ACCOUNT/data',
    AGENT_WALLET_ACCOUNT_ERROR: 'AGENT_WALLET_ACCOUNT/error',

    CUSTOMER_VALIDATION_FETCH: 'CUSTOMER_VALIDATION/fetch',
    CUSTOMER_VALIDATION_SUCCESS: 'CUSTOMER_VALIDATION/success',
    CUSTOMER_VALIDATION_ERROR: 'CUSTOMER_VALIDATION/error',
    
    CUSTOMER_CASH_DEPOSIT_FETCH: 'CUSTOMER_CASH_DEPOSIT/fetch',
    CUSTOMER_CASH_DEPOSIT_SUCCESS: 'CUSTOMER_CASH_DEPOSIT/success',
    CUSTOMER_CASH_DEPOSIT_ERROR: 'CUSTOMER_CASH_DEPOSIT/error',
    /**
    *
    */
};
export default actionType;