const actionType = {
    AGENT_LOGIN_SUCCESS: "AGENT_LOGIN_SUCCESS",
    AGENT_LOGIN_FAILURE: "AGENT_LOGIN_FAILURE",
    AGENT_LINKING_SUCCESS:"AGENT_LINKING_SUCCESS",
    AGENT_LINKING_FAILURE:"AGENT_LINKING_FAILURE"
};
export default actionType;