const initialState = {
  adminLoginStatus: false,
  merchantListStatus: false,
  merchantListData: null,
  merchantKycStatus: false,
  merchantKycData: null,
  summaryStatus: false,
  summaryData: null,
  merchantSecondPendingListStatus: false,
  merchantSecondPendingListData: null,
  merchantFirstPendingListStatus: false,
  merchantFirstPendingListData: null,
  currencyStatus:false,
  currencyList:null,
  merchantRevenueStatus: false,
  merchantRevenueList: null,
  amountCollectedStatus: false,
  amountCollectedData:null,
  accessHistoryStatus: false,
  accessHistoryData:null,
  clientList:[],
  clientListStatus:false,
  secondApprovalclientList:[],
  secondApprovalclientListStatus:false,
  getCurrencyListData: [],
  getCurrencyListDataStatus: false,
  getTransactionFeeListsStatus:false,
  getTransactionFeeLists: [],
  permissionsLists:null,
  permissionsStatus:false,
};

export default initialState;
